<?php

return [
/*    \App\Income::QIWI => [
        \App\Account::CURRENCY_USD => '123',
        \App\Account::CURRENCY_EUR => '123',
        \App\Account::CURRENCY_RUB => '123',
        \App\Account::CURRENCY_BTC_ONE => '123',
        \App\Account::CURRENCY_BTC_TWO => '123',
    ],
    \App\Income::PAYEER => [
        \App\Account::CURRENCY_USD => 'В комментариях укажите Ваш уникальный ID для перевода',
        \App\Account::CURRENCY_EUR => 'В комментариях укажите Ваш уникальный ID для перевода',
        \App\Account::CURRENCY_RUB => '123',
        \App\Account::CURRENCY_BTC_ONE => '123',
        \App\Account::CURRENCY_BTC_TWO => '123',
    ],
    \App\Income::PERFECT_MONEY => [
        \App\Account::CURRENCY_USD => 'В комментариях укажите Ваш уникальный ID для перевода',
        \App\Account::CURRENCY_EUR => 'В комментариях укажите Ваш уникальный ID для перевода',
        \App\Account::CURRENCY_RUB => '123',
        \App\Account::CURRENCY_BTC_ONE => '123',
        \App\Account::CURRENCY_BTC_TWO => '123',
    ],
    \App\Income::BITCOIN => [
        \App\Account::CURRENCY_USD => '123',
        \App\Account::CURRENCY_EUR => '123',
        \App\Account::CURRENCY_RUB => '123',
        \App\Account::CURRENCY_BTC_ONE => 'Комментарий указывать не нужно',
        \App\Account::CURRENCY_BTC_TWO => '123',
    ],
    \App\Income::CARD => [
        \App\Account::CURRENCY_USD => '123',
        \App\Account::CURRENCY_EUR => '123',
        \App\Account::CURRENCY_RUB => '123',
        \App\Account::CURRENCY_BTC_ONE => '123',
        \App\Account::CURRENCY_BTC_TWO => '123',
    ],
    \App\Income::ADVACASH => [
        \App\Account::CURRENCY_USD => '123',
        \App\Account::CURRENCY_EUR => '123',
        \App\Account::CURRENCY_RUB => '123',
        \App\Account::CURRENCY_BTC_ONE => '123',
        \App\Account::CURRENCY_BTC_TWO => '123',
    ],
    \App\Income::YANDEX => [
        \App\Account::CURRENCY_USD => '123',
        \App\Account::CURRENCY_EUR => '123',
        \App\Account::CURRENCY_RUB => '123',
        \App\Account::CURRENCY_BTC_ONE => '123',
        \App\Account::CURRENCY_BTC_TWO => '123',
    ],
    \App\Income::ETH => [
        \App\Account::CURRENCY_USD => '123',
        \App\Account::CURRENCY_EUR => '123',
        \App\Account::CURRENCY_RUB => '123',
        \App\Account::CURRENCY_BTC_ONE => '123',
        \App\Account::CURRENCY_BTC_TWO => 'Комментарий указывать не нужно',
    ],
    \App\Income::TETHER_ERC_20 => [
        \App\Account::CURRENCY_USD => 'Комментарий указывать не нужно',
        \App\Account::CURRENCY_EUR => '123',
        \App\Account::CURRENCY_RUB => '123',
        \App\Account::CURRENCY_BTC_ONE => '123',
        \App\Account::CURRENCY_BTC_TWO => '123',
    ],
    \App\Income::RIPPLE => [
        \App\Account::CURRENCY_USD => 'Комментарий указывать не нужно',
        \App\Account::CURRENCY_EUR => '123',
        \App\Account::CURRENCY_RUB => '123',
        \App\Account::CURRENCY_BTC_ONE => '123',
        \App\Account::CURRENCY_BTC_TWO => '123',
    ],
    \App\Income::LITECOIN => [
        \App\Account::CURRENCY_USD => 'Комментарий указывать не нужно',
        \App\Account::CURRENCY_EUR => '123',
        \App\Account::CURRENCY_RUB => '123',
        \App\Account::CURRENCY_BTC_ONE => '123',
        \App\Account::CURRENCY_BTC_TWO => '123',
    ],
    \App\Income::DASH => [
        \App\Account::CURRENCY_USD => 'Комментарий указывать не нужно',
        \App\Account::CURRENCY_EUR => '123',
        \App\Account::CURRENCY_RUB => '123',
        \App\Account::CURRENCY_BTC_ONE => '123',
        \App\Account::CURRENCY_BTC_TWO => '123',
    ],
    \App\Income::BITCOIN_CASH => [
        \App\Account::CURRENCY_USD => 'Комментарий указывать не нужно',
        \App\Account::CURRENCY_EUR => '123',
        \App\Account::CURRENCY_RUB => '123',
        \App\Account::CURRENCY_BTC_ONE => 'Комментарий указывать не нужно',
        \App\Account::CURRENCY_BTC_TWO => '123',
    ],
    \App\Income::MONERO => [
        \App\Account::CURRENCY_USD => 'Комментарий указывать не нужно',
        \App\Account::CURRENCY_EUR => '123',
        \App\Account::CURRENCY_RUB => '123',
        \App\Account::CURRENCY_BTC_ONE => '123',
        \App\Account::CURRENCY_BTC_TWO => 'Комментарий указывать не нужно',
    ],*/
    \App\Account::CURRENCY_XMR => 'zafasdf',
    \App\Account::CURRENCY_UMEE => 'zafasdf',
    \App\Account::CURRENCY_DOT => 'zafasdf',
    \App\Account::CURRENCY_XRP => 'zafas23df',
    \App\Account::CURRENCY_USD_PM => '))))))zafas23df',
];
